# Generated by Django 3.2.6 on 2021-08-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=0, default=100, max_digits=8)),
                ('measure', models.CharField(choices=[('ml', 'ml'), ('gram', 'gram')], default='gram', max_length=4)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredient', models.ManyToManyField(to='nutrition.Ingredient')),
            ],
        ),
    ]
