# Generated by Django 3.2.6 on 2021-08-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
