# Generated by Django 3.2.6 on 2021-08-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_auto_20210824_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=8),
        ),
    ]
