# Generated by Django 3.2.6 on 2021-08-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_dish_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(to='nutrition.Ingredient'),
        ),
    ]
