# Generated by Django 3.2.6 on 2021-08-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_dish_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(null=True, to='nutrition.Dish'),
        ),
    ]
