# Generated by Django 3.2.6 on 2021-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_auto_20210824_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='dish',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=models.ManyToManyField(to='nutrition.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=8),
        ),
    ]
