# Generated by Django 3.2.6 on 2021-08-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_auto_20210824_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('main_ingredient', models.CharField(max_length=500)),
                ('optional_ingredient', models.CharField(blank=True, max_length=500)),
                ('spicies', models.CharField(blank=True, max_length=500)),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='kcal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
