# Generated by Django 3.2.6 on 2021-08-27 04:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_auto_20210827_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
