# Generated by Django 3.2.6 on 2021-08-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_recipe_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
